/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ClubMemberLocationsEntity {
  'ClubMemberID': number;
  'EndDate'?: Date | null;
  'LocationID': number;
  'StartDate'?: Date | null;
}
export interface ClubMembersEntity {
  'Address'?: string | null;
  'City'?: string | null;
  'ClubMemberID'?: number;
  'ClubMembershipNumber': string;
  'DateOfBirth'?: Date | null;
  'FirstName'?: string | null;
  'LastName'?: string | null;
  'MedicalCardNumber': string;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'Role'?: 'GoalKeeper' | 'Defender' | 'Midfielder' | 'Forward' | null;
  'SocialSecurityNumber': string;
  'Status'?: 'Active' | 'Inactive' | null;
  'TeamType'?: string | null;
  'TelephoneNumber'?: string | null;
}
export interface ClubMemberTeamsEntity {
  'ClubMemberID'?: number | null;
  'EndDate'?: Date | null;
  'StartDate'?: Date | null;
  'TeamID'?: number | null;
}
export interface FamilyMemberEntity {
  'Address'?: string | null;
  'City'?: string | null;
  'DateOfBirth'?: Date | null;
  'EmailAddress'?: string | null;
  'FamilyMemberID'?: number;
  'FirstName'?: string | null;
  'LastName'?: string | null;
  'LocationID'?: number | null;
  'MedicalCardNumber': string;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'SocialSecurityNumber': string;
  'TelephoneNumber'?: string | null;
}
export interface FamilyMemberLocationsEntity {
  'EndDate'?: Date | null;
  'FamilyMemberID': number;
  'LocationID': number;
  'StartDate'?: Date | null;
}
export interface FamilyRelatedEntity {
  'ClubMemberID': number;
  'EndDate'?: Date | null;
  'FamilyMemberID': number;
  'Relationship'?: string | null;
  'StartDate'?: Date | null;
}
export interface LocationEntity {
  'Address'?: string | null;
  'Capacity'?: number | null;
  'City'?: string | null;
  'GeneralManager'?: string | null;
  'LocationID'?: number;
  'Name'?: string | null;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'TelephoneNumber'?: string | null;
  'Type'?: 'Head' | 'Branch' | null;
  'WebAddress'?: string | null;
}
export interface PersonnelEntity {
  'Address'?: string | null;
  'City'?: string | null;
  'DateOfBirth'?: Date | null;
  'EmailAddress'?: string | null;
  'EndDate'?: Date | null;
  'FirstName'?: string | null;
  'LastName'?: string | null;
  'Mandate'?: 'Volunteer' | 'Salaried' | null;
  'MedicalCardNumber': string;
  'PersonnelID'?: number;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'Role'?: string | null;
  'SocialSecurityNumber': string;
  'StartDate'?: Date | null;
  'TelephoneNumber'?: string | null;
}
export interface PersonnelLocationsEntity {
  'EndDate'?: Date | null;
  'LocationID': number;
  'PersonnelID': number;
  'StartDate': Date;
}
export interface SecondaryFamilyMemberEntity {
  'FamilyMemberID'?: number | null;
  'FirstName'?: string | null;
  'LastName'?: string | null;
  'SecondaryFamilyMemberID'?: number;
  'TelephoneNumber'?: string | null;
}
export interface SecondaryFamilyRelatedEntity {
  'ClubMemberID'?: number | null;
  'Relationship'?: string | null;
  'SecondaryFamilyMemberID'?: number | null;
}
export interface SessionsEntity {
  'LocationID'?: number | null;
  'SessionID'?: number;
  'TypeOfSession'?: string | null;
}
export interface TeamFormationEntity {
  'Date'?: Date | null;
  'Score'?: number | null;
  'TeamFormationID'?: number;
  'TeamType'?: string | null;
  'Time'?: Date | null;
}
export interface TeamsEntity {
  'HeadCoach'?: string | null;
  'LocationID'?: number | null;
  'TeamID'?: number;
  'TeamName'?: string | null;
  'TeamType'?: string | null;
}
