/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ClubMembersEntity {
  'Address'?: string | null;
  'City'?: string | null;
  'ClubMemberID'?: number;
  'DateOfBirth': Date;
  'FamilyMemberID': number;
  'FirstName': string;
  'LastName': string;
  'LocationID': number;
  'MedicareCardNumber'?: string | null;
  'MembershipNumber': number;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'SocialSecurityNumber': string;
  'Status': 'Active' | 'Inactive';
  'TeamType': 'Boys' | 'Girls';
  'TelephoneNumber'?: string | null;
}
export interface ClubMemberTeamsEntity {
  'ClubMemberID': number;
  'ClubMemberTeamID'?: number;
  'EndDate'?: Date | null;
  'StartDate': Date;
  'TeamID': number;
}
export interface FamilyMemberLocationsEntity {
  'EndDate'?: Date | null;
  'FamilyMemberID': number;
  'FamilyMemberLocationID'?: number;
  'LocationID': number;
  'StartDate': Date;
}
export interface FamilyMembersEntity {
  'Address'?: string | null;
  'City'?: string | null;
  'DateOfBirth': Date;
  'EmailAddress'?: string | null;
  'FamilyMemberID'?: number;
  'FirstName': string;
  'LastName': string;
  'LocationID': number;
  'MedicareCardNumber'?: string | null;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'SocialSecurityNumber': string;
  'TelephoneNumber'?: string | null;
  'Type': 'Father' | 'Mother' | 'GrandFather' | 'GrandMother' | 'Tutor' | 'Partner' | 'Friend' | 'Other';
}
export interface LocationsEntity {
  'Address': string;
  'Capacity'?: number | null;
  'City': string;
  'GeneralManagerName'?: string | null;
  'LocationID'?: number;
  'Name': string;
  'PhoneNumber'?: string | null;
  'PostalCode': string;
  'Province': string;
  'Type': 'Head' | 'Branch';
  'WebAddress'?: string | null;
}
export interface PersonnelEntity {
  'Address'?: string | null;
  'City'?: string | null;
  'DateOfBirth': Date;
  'EmailAddress'?: string | null;
  'FirstName': string;
  'LastName': string;
  'Mandate': 'Volunteer' | 'Salaries';
  'MedicareCardNumber'?: string | null;
  'PersonnelID'?: number;
  'PostalCode'?: string | null;
  'Province'?: string | null;
  'Role': 'Administrator' | 'Trainer' | 'Other';
  'SocialSecurityNumber': string;
  'TelephoneNumber'?: string | null;
}
export interface PersonnelLocationsEntity {
  'EndDate'?: Date | null;
  'LocationID': number;
  'PersonnelID': number;
  'PersonnelLocationID'?: number;
  'StartDate': Date;
}
export interface TeamsEntity {
  'LocationID': number;
  'TeamID'?: number;
  'TeamName': string;
  'TeamType': 'Boys' | 'Girls';
}
